project:
  type: website
  output-dir: docs

website:
  title: "Tomas Kristijonas Uždavinys"
  description: "This is personal Blog."
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - portfolio.qmd
format:
  html:
    theme: litera
    css: styles.css

editor: visual